{% set data = load_setup_py_data() %}

package:
  name: "pymt_pynetlogo"
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - bmi-tester
    - model_metadata
  imports:
    - pymt_pynetlogo
  commands:

about:
  summary: Python package that wraps the pymt_pynetlogo BMI.
  home: https://github.com/pymt-lab/pymt_pynetlogo
  license: MIT License
  license_file: LICENSE
  dev_url: https://github.com/pymt-lab/pymt_pynetlogo
