# An environment for building the pyNetLogo BMI example.
name: logo
channels:
  - conda-forge
dependencies:
  - python =3
  - pip
  - nox
  - bmipy
  - numpy
  - scipy
  - pandas
  - jpype1
  - matplotlib
  - jupyter
  - pytest
  - pytest-cov
  - pytest-datadir
  - coverage
  - zest.releaser
  - black
  - ruff
  - isort
  - pip:
    - pynetlogo
